### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ratbeard** [karnowski/blue-ridge-tmbundle#1]
I'm not able to get this bundle to install.  I ran the steps and reloaded bundles, both through the UI and w/: 

```
osascript -e 'tell app "TextMate" to reload bundles'
```

but it didn't show up.  I was able to install the Screw Unit bundle after trying this bundle, no problems.  Could there be some issue with copying the screw unit files, maybe the uuids?  I tried installing this before screw unit so I'm not sure how that would be the case ..

I'm running textmate Version 1.5.8 (1505)

**Comment by ratbeard** [comment]
Any updates???

**Comment by karnowski** [comment]
Sorry @ratbeard, but I haven't used TextMate in a long, long while.  I don't know of anyone that is maintaining this tmbundle anymore.
